/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class study_polytech_scraper_phash_PHashCalculator */

#ifndef _Included_study_polytech_scraper_phash_PHashCalculator
#define _Included_study_polytech_scraper_phash_PHashCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     study_polytech_scraper_phash_PHashCalculator
 * Method:    calculateHashes
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_study_polytech_scraper_phash_PHashCalculator_calculateHashes
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
